spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://172.17.0.0:5432/docker
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
