spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: postgres
  datasource:
    url: jdbc:postgresql://postgresserver/docker
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
