spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: postgres
  datasource:
    url: jdbc:postgresql://${POSTGRES_PORT_3306_TCP_ADDR}:${POSTGRES_PORT_3306_TCP_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
