spring:
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: postgres
  datasource:
    url: jdbc:postgresql://postgresserver/docker
    username: dbuser
    password: dbpassword
    driver-class-name: org.postgresql.Driver
